import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Lyrics from './components/Lyrics'
// import songs from './api'

const inter = Inter({ subsets: ['latin'] })

let songList = [
  {
      "name": "King of kings",
      "lyricLink": "https://www.azlyrics.com/lyrics/hillsongworship/kingofkings.html",
      "youtubeLink": "https://youtu.be/GKE_gkgEac4",
  },
  {
      "name": "Reckless Love",
      "lyricLink": "https://www.azlyrics.com/lyrics/coryasbury/recklesslove.html",
      "youtubeLink": "https://youtu.be/6xx0d3R2LoU",
  },
  {
      "name": "Jesus paid it all",
      "lyricLink": "https://www.azlyrics.com/lyrics/kimwalkersmith/jesuspaiditall.html",
      "youtubeLink": "https://youtu.be/Ymkl0t0FOcw",
  },
  {
      "name": "No Longer Slaves",
      "lyricLink": "https://www.azlyrics.com/lyrics/bethelmusic/nolongerslaves.html",
      "youtubeLink": "https://youtu.be/2QigyB50yGw",
  },
  {
      "name": "Build My life",
      "lyricLink": "https://www.azlyrics.com/lyrics/patbarrett/buildmylife.html",
      "youtubeLink": "https://youtu.be/Z32HiCoFzlU",
  },
  {
      "name": "Way Maker",
      "lyricLink": "https://www.azlyrics.com/lyrics/leeland/waymaker.html",
      "youtubeLink": "https://youtu.be/iJCV_2H9xD0",
  }
]

export default function Home() {


  return (
    <>
      <Head>
        <title>Lyrics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Lyrics songList={songList} />
    </>
  )
}
